# Generated by Django 3.1.2 on 2020-11-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('population_all', models.IntegerField(default=0)),
                ('school', models.FloatField()),
                ('park', models.FloatField()),
            ],
        ),
    ]
