# Generated by Django 3.1.3 on 2020-11-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_dong_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dong',
            old_name='school',
            new_name='school_elementary',
        ),
    ]
