# Generated by Django 3.1.3 on 2020-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_auto_20201127_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dong',
            name='output',
        ),
        migrations.AddField(
            model_name='dong',
            name='air_pollution',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dong',
            name='cctv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dong',
            name='hagwon',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dong',
            name='leisure',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dong',
            name='library',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dong',
            name='medical',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dong',
            name='restaurant',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dong',
            name='school_high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dong',
            name='school_middle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dong',
            name='senior_center',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dong',
            name='sport_facility',
            field=models.FloatField(default=0),
        ),
    ]
