# Generated by Django 3.1.3 on 2020-11-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0008_searchkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dong',
            name='cctv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='hagwon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='kindergarten',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='leisure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='library',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='medical',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='park',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='restaurant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='school_elementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='school_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='school_middle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='school_special',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='senior_center',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dong',
            name='sport_facility',
            field=models.IntegerField(default=0),
        ),
    ]
